### ISSUE TITLE
Non Linear eGalax TouchScreen

### ISSUE THREAD

**Issue by mabeett** [tias/xinput_calibrator#63]
I have a 21.5" LED Touch Monitor with usb touchpanel 

```
ID 0eef:0001 D-WAV Scientific Co., Ltd eGalax TouchScreen
```

I tried to install and configure it in Ubuntu  Linux 14.04.2,. I installed the xinput-calibrator package (Version: 0.7.5+git20140201-1) but I have no good results.

Debugging the panel output with evtest I see that the output panel is not as linear as it shoud! 

Do you know if does evdev driver support linearization or where to ask for it? 

Thanks,

**Comment by merge** [comment]
[tslib](https://github.com/kergoth/tslib) offers linearization (using `module linear` in ts.conf and manually running ts_calibrate once, to generate the config file for this linear filter module). tslib also ships with a daemon program called ts_uinput that creates a standard evdev input device you can then use in any system.
